name: Test C App

description: "tet"

runs:
  using: composite

  steps:
    - name: wakeup
      shell: bash
      run: echo "wakeup"
    - name: brush your teeth
      shell: bash
      run: echo "brush your teeth"

