name: "01-building-blocks"
run-name: "${{github.actor}} is running Test"

on:
  push:
  workflow_dispatch:
env:
  first_name: Benedict

jobs:
  echo-hello:
    runs-on: ubuntu-latest

    steps:
      - name: "Say hello"
        run: echo "Hello world"

  echo-goodbye:
    runs-on: ubuntu-latest
    env:
      job_name: engineeratechogoodbye

    steps:

      - name: "Failed step"
        run: echo "good Scores $first_name and $step1_name"
        env:
          step1_name: fromstep1
      - name: "testing branch name"
        if: ${{ env.first_name=='Benedict'}}
        run: echo "Testing ${{env.first_name}}"  

      - name: "scores step"
        run: echo "good scores $first_name and $job_name and $step1_name"

      - name: "Say goodbye"
        run: echo "Goodbye Ben"
