name: "configuration files"

on:
  push:
  workflow_dispatch: 

jobs:
  parur:
    runs-on: ubuntu-latest
    environment:
      name: DEV
    
    steps:
      - name: "Good of1"
        run: echo "god ${{vars.DEV_NAME}}"
