name: 03-composite workflow run

on: 
  push:
  workflow_dispatch:

jobs:
  school:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      
      - uses: ./.github/actions/test-app

      - name:  going school
        run: echo "going to school"

